# Generated by Django 5.2.4 on 2026-01-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('manager', 'Project Manager'), ('staff', 'Staff'), ('student', 'Student')], default='staff', max_length=10),
        ),
    ]
