# Generated by Django 5.2.4 on 2026-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('manager', 'Project Manager'), ('financialadmin', 'Financial Admin'), ('staff', 'Staff'), ('student', 'Student')], default='staff', max_length=15),
        ),
    ]
