# Generated by Codex on 2026-05-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_researchcentre_costcentre_research_centre'),
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Admin'),
                    ('dean', 'Dean'),
                    ('centrehead', 'Centre Head'),
                    ('supervisor', 'Supervisor'),
                    ('manager', 'Project Manager'),
                    ('financialadmin', 'Financial Admin'),
                    ('staff', 'Staff'),
                    ('student', 'Student'),
                ],
                default='staff',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='research_centre',
            field=models.ForeignKey(
                blank=True,
                help_text='Research centre this user belongs to. Required for centre heads.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='adminpanel.researchcentre',
            ),
        ),
    ]
