# Generated by Django 5.2.4 on 2025-08-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in-progress', 'In Progress'), ('on-hold', 'On Hold'), ('completed', 'Completed')], default='planning', max_length=20),
        ),
    ]
