# Generated by Django 5.2.4 on 2026-01-29 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_chatmessage_recipient_alter_chatmessage_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
