# Generated by Django 5.2.4 on 2026-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_studentprofile_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='messages/'),
        ),
    ]
