# Generated by Django 5.2.4 on 2026-05-25 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_costcentre_client_name'),
        ('projects', '0006_chatmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='research_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='adminpanel.researchcentre'),
        ),
    ]
