# Generated by Django 5.2.4 on 2025-08-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
