# Generated by Django 5.2.4 on 2026-01-27 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The actual media file', upload_to='system_media/%Y/%m/%d/')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=50)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this media is still in use')),
                ('description', models.TextField(blank=True, help_text='Description of the media file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Media',
                'verbose_name_plural': 'System Media',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['uploaded_by', '-uploaded_at'], name='adminpanel__uploade_1345dd_idx'), models.Index(fields=['file_type'], name='adminpanel__file_ty_c2f4f2_idx'), models.Index(fields=['is_active'], name='adminpanel__is_acti_53922a_idx')],
            },
        ),
    ]
