# Generated by Django 5.2.4 on 2026-01-27 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_systemmedia'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmedia',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_media_files', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='systemmedia',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True),
        ),
        migrations.AddField(
            model_name='systemmedia',
            name='purpose',
            field=models.CharField(choices=[('submission', 'Student Submission'), ('feedback', 'Supervisor Feedback'), ('template', 'Project Template'), ('manuscript', 'Paper Manuscript'), ('progress_update', 'Progress Update'), ('general', 'General Upload')], default='general', help_text='Purpose/use of the file in system', max_length=50),
        ),
        migrations.AddIndex(
            model_name='systemmedia',
            index=models.Index(fields=['purpose'], name='adminpanel__purpose_6e0c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmedia',
            index=models.Index(fields=['content_type', 'object_id'], name='adminpanel__content_c707d5_idx'),
        ),
    ]
