# Generated by Django 5.2.4 on 2026-01-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_systemmedia_content_type_systemmedia_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmedia',
            name='file_blob',
            field=models.BinaryField(blank=True, help_text='File content stored in database (for fallback/backup)', null=True),
        ),
        migrations.AddField(
            model_name='systemmedia',
            name='stored_in_db',
            field=models.BooleanField(default=False, help_text='Whether file is backed up in database'),
        ),
    ]
