# Generated by Django 5.2.4 on 2026-01-29 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_systemmedia_file_blob_systemmedia_stored_in_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField(auto_now_add=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('clocked_in', 'Clocked In'), ('clocked_out', 'Clocked Out')], default='clocked_in', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clock_in_time'],
                'indexes': [models.Index(fields=['employee', '-clock_in_time'], name='adminpanel__employe_49cadc_idx'), models.Index(fields=['status'], name='adminpanel__status_bd0c98_idx')],
            },
        ),
    ]
