# Generated by Django 5.2.4 on 2026-02-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_clockinrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='total_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='CostCentrePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, help_text='e.g., Project Name, Phase 1', max_length=255)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='adminpanel.costcentre')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
