# Generated by Django 5.2.4 on 2026-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_costcentre_total_received_costcentrepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentre',
            name='moa_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Memorandum of Understanding - Total expected/budgeted amount', max_digits=12, null=True),
        ),
    ]
