# Generated by Django 5.2.4 on 2026-02-04 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_costcentre_moa_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_cost_centre', 'Created Cost Centre'), ('edit_cost_centre', 'Edited Cost Centre'), ('delete_cost_centre', 'Deleted Cost Centre'), ('create_expenditure', 'Created Expenditure'), ('edit_expenditure', 'Edited Expenditure'), ('delete_expenditure', 'Deleted Expenditure'), ('create_payment', 'Created Payment'), ('delete_payment', 'Deleted Payment')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveIntegerField()),
                ('entity_name', models.CharField(max_length=255)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='adminpanel__timesta_0914cd_idx'), models.Index(fields=['entity_type'], name='adminpanel__entity__e8c760_idx'), models.Index(fields=['action'], name='adminpanel__action_fac12d_idx')],
            },
        ),
    ]
