# Generated by Django 5.2.4 on 2026-02-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinrecord',
            name='clock_in_time',
            field=models.DateTimeField(),
        ),
    ]
