# Generated by Django 5.2.4 on 2026-02-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_useravailability_userleaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='date_from',
            field=models.DateField(blank=True, help_text='Start date of salary/expenditure period', null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='date_to',
            field=models.DateField(blank=True, help_text='End date of salary/expenditure period', null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='month',
            field=models.CharField(blank=True, help_text='Legacy field - use date_from and date_to instead', max_length=20, null=True),
        ),
    ]
