# Generated by Codex on 2026-05-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_alter_costcentre_code_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='costcentre',
            name='research_centre',
            field=models.ForeignKey(
                blank=True,
                help_text='Research centre this financial cost centre belongs to.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cost_centres',
                to='adminpanel.researchcentre',
            ),
        ),
    ]
