# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_researchcentre_costcentre_research_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='oracle_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
