# Generated by Django 5.2.4 on 2026-05-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_costcentre_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentre',
            name='phase_1_due_date',
            field=models.DateField(blank=True, help_text='Client phase 1 due date', null=True),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='phase_2_due_date',
            field=models.DateField(blank=True, help_text='Client phase 2 due date', null=True),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='phase_3_due_date',
            field=models.DateField(blank=True, help_text='Client phase 3 due date', null=True),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='phase_4_due_date',
            field=models.DateField(blank=True, help_text='Client phase 4 due date', null=True),
        ),
    ]
