# Generated by Django 5.2.4 on 2026-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_costcentre_phase_1_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentre',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='company_name',
            field=models.CharField(blank=True, help_text='Registered company or organisation name', max_length=200),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='company_registration_number',
            field=models.CharField(blank=True, help_text='CIPC or company registration number', max_length=80),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contact_person_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='crm_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='vat_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
