# Generated by Codex on 2026-07-02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_costcentre_company_address_costcentre_company_email_and_more'),
        ('projects', '0007_project_research_centre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('meeting_minutes', 'Meeting Minutes'), ('discussion', 'Discussion'), ('comment', 'Comment')], default='discussion', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('engagement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(help_text='Meeting minutes, engagement notes, or discussion summary.')),
                ('proposal_summary', models.TextField(blank=True, help_text='Capture what your centre proposed so future teams can see the previous approach.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to='adminpanel.costcentre')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_logs', to='projects.project')),
                ('research_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_logs', to='adminpanel.researchcentre')),
            ],
            options={
                'ordering': ['-engagement_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['engagement_date'], name='adminpanel__engagem_600f48_idx'),
                    models.Index(fields=['project'], name='adminpanel__project_8f50fd_idx'),
                    models.Index(fields=['cost_centre'], name='adminpanel__cost_ce_5aa151_idx'),
                ],
            },
        ),
    ]
