# Generated by Django 5.2.4 on 2026-07-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_engagementlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='engagementlog',
            new_name='adminpanel__engagem_bb9667_idx',
            old_name='adminpanel__engagem_600f48_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementlog',
            new_name='adminpanel__project_5f2e51_idx',
            old_name='adminpanel__project_8f50fd_idx',
        ),
        migrations.RenameIndex(
            model_name='engagementlog',
            new_name='adminpanel__cost_ce_97d99c_idx',
            old_name='adminpanel__cost_ce_5aa151_idx',
        ),
    ]
