from django.urls import path
from . import views
from . import supervisors

urlpatterns = [
    # Supervisor Portal Routes
    path('supervisor-portal/dashboard/', supervisors.supervisor_dashboard, name='supervisor_dashboard_portal'),
    path('supervisor-portal/messages/', supervisors.supervisor_messages, name='supervisor_messages'),
    path('supervisor-portal/student/<int:student_id>/', supervisors.supervisor_student_detail, name='supervisor_student_detail'),
    
    # Admin Routes
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin_book/', views.admin_book, name='admin_book'),
    path('update-book-status/<int:book_id>/', views.update_book_status, name='update_book_status'),
    path('app_kanban/', views.app_kanban, name='app_kanban'),
    path('admin_journal/', views.admin_journal, name='admin_journal'),
    path('admin_ganttchart/', views.admin_ganttchart, name='admin_ganttchart'),
    path('overview/', views.overview, name='overview'),
    path('finance/', views.finance, name='finance'),
    path('admin_kanban/', views.admin_kanban, name='admin_kanban'),
    path('supervisor/', views.supervisor_dashboard, name='supervisor_dashboard'),
    path('supervisor/student/<int:student_id>/', views.student_detail_view, name='student_detail'),
    path('supervisor_dashboard/', views.supervisor_dashboard, name='supervisor_dashboard'),
    path('finance/add-cost-centre/', views.add_cost_centre, name='add_cost_centre'),
    path('finance/expenditures/<int:cost_centre_id>/', views.get_expenditures, name='get_expenditures'),
    path('feedback/<int:submission_id>/', views.provide_feedback, name='provide_feedback'),
    path('finance/add-expenditure/', views.add_expenditure, name='add_expenditure'),
    path('finance/delete-cost-centre/<int:pk>/', views.delete_cost_centre, name='delete_cost_centre'),
    path('finance/edit-cost-centre/<int:pk>/', views.edit_cost_centre, name='edit_cost_centre'),
    path('finance/edit-expenditure/<int:pk>/', views.edit_expenditure, name='edit_expenditure'),
    path('finance/delete-expenditure/<int:pk>/', views.delete_expenditure, name='delete_expenditure'),
    # path('admin/user-kanban/<int:user_id>/', views.admin_user_kanban, name='admin_user_kanban'),
    path('user-kanban/<int:user_id>/', views.admin_user_kanban, name='admin_user_kanban'),
    path('assign-project/', views.assign_project, name='admin_assign_project'),
    path('create-project/', views.create_project, name='admin_create_project'),
    path('update-project/<int:project_id>/', views.update_project, name='admin_update_project'),
    path('delete-project/<int:project_id>/', views.delete_project, name='admin_delete_project'),
    path('projects-json/', views.get_projects_json, name='admin_get_projects_json'),
    path('api/gantt-data/', views.gantt_data_api, name='gantt_data_api'),
    path('admin/project-tasks/<str:project_name>/', views.project_task_detail, name='project_task_detail'),
    path('admin/update-task-progress/<int:task_id>/', views.update_task_progress, name='update_task_progress'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('create-user/', views.create_user, name='create_user'),
    path('activate-user/<int:user_id>/', views.activate_user, name='activate_user'),
    path('deactivate-user/<int:user_id>/', views.deactivate_user, name='deactivate_user'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('register_users/',views.register_users,name='register_users'),
        path('load-student-manual/', views.load_student_manual, name='load_student_manual'),
    path('load-students-csv/', views.load_students_csv, name='load_students_csv'),
    path('notifications/create/', views.create_notification, name='create_notification'),
]
