# Generated by Django 5.2.4 on 2026-02-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_papercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='papercomment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
