# Generated by Django 5.2.4 on 2026-02-04 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_papercomment_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_external', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('conference_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_author', models.CharField(max_length=255)),
                ('co_authors', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('presenting', 'Presenting'), ('presented', 'Presented'), ('rejected', 'Rejected')], max_length=50)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('paper', models.FileField(blank=True, null=True, upload_to='conference_papers/')),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('conference_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to=settings.AUTH_USER_MODEL)),
                ('reviewers', models.ManyToManyField(blank=True, related_name='reviewed_conferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
