# Generated by Django 5.2.4 on 2026-02-04 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_conference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='decision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('circulation', 'In Circulation'), ('ready-submission', 'Ready for Submission'), ('returned-feedback', 'Returned with Feedback'), ('submitted', 'Submitted'), ('under-review', 'Under Review'), ('accepted', 'Accepted'), ('accepted-minor', 'Accepted - Minor Revisions'), ('accepted-major', 'Accepted - Major Revisions'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='PaperStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='manager.paper')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
