# Generated by Django 5.2.4 on 2026-02-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_paper_decision_date_paper_feedback_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='assigned_reviewers',
            field=models.ManyToManyField(blank=True, related_name='conferences_to_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='co_authors_users',
            field=models.ManyToManyField(blank=True, related_name='co_authored_conferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='lead_author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_conferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paper',
            name='assigned_reviewers',
            field=models.ManyToManyField(blank=True, related_name='papers_to_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paper',
            name='co_authors_users',
            field=models.ManyToManyField(blank=True, related_name='co_authored_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paper',
            name='lead_author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_papers', to=settings.AUTH_USER_MODEL),
        ),
    ]
