# Generated by Django 5.2.4 on 2026-02-04 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_conference_assigned_reviewers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('paper', 'Research Paper'), ('conference', 'Conference')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('object_title', models.CharField(blank=True, max_length=500, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='manager_cha_content_583e87_idx'), models.Index(fields=['changed_by'], name='manager_cha_changed_9786ea_idx'), models.Index(fields=['-changed_at'], name='manager_cha_changed_a3c343_idx')],
            },
        ),
    ]
